"""Create clinical data models

Revision ID: 58ebb0c75e66
Revises: 5ea2bbced759
Create Date: 2026-09-20 14:42:51.133438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58ebb0c75e66'
down_revision = '5ea2bbced759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('work_study', sa.String(length=200), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=30), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('medical_flags', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_phone'), ['phone'], unique=False)

    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('procedure', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('booked', 'completed', 'cancelled')", name='ck_appointment_status'),
    sa.CheckConstraint('duration > 0', name='ck_appointment_duration'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_patient_id'), ['patient_id'], unique=False)

    op.create_table('odontograms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('tooth_number', sa.Integer(), nullable=False),
    sa.Column('tooth_mode', sa.String(length=20), nullable=False),
    sa.Column('condition', sa.String(length=100), nullable=True),
    sa.Column('procedure', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("tooth_mode IN ('permanent', 'primary')", name='ck_odontogram_tooth_mode'),
    sa.CheckConstraint('tooth_number >= 1 AND tooth_number <= 32', name='ck_odontogram_tooth_number'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'tooth_number', 'tooth_mode', name='uq_odontogram_patient_tooth_mode')
    )
    with op.batch_alter_table('odontograms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_odontograms_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_odontograms_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_odontograms_patient_id'), ['patient_id'], unique=False)

    op.create_table('prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescriptions_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescriptions_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescriptions_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescriptions_patient_id'), ['patient_id'], unique=False)

    op.create_table('treatment_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('tooth_number', sa.Integer(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('procedure', sa.String(length=150), nullable=True),
    sa.Column('fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("priority IN ('low', 'medium', 'high')", name='ck_treatment_plan_priority'),
    sa.CheckConstraint("status IN ('planned', 'accepted', 'scheduled', 'in-progress', 'completed', 'cancelled')", name='ck_treatment_plan_status'),
    sa.CheckConstraint('tooth_number IS NULL OR (tooth_number >= 1 AND tooth_number <= 85)', name='ck_treatment_plan_tooth_number'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('treatment_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_treatment_plans_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_treatment_plans_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_treatment_plans_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_treatment_plans_patient_id'), ['patient_id'], unique=False)

    op.create_table('treatments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('tooth_number', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('procedure', sa.String(length=150), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('planned', 'accepted', 'scheduled', 'in-progress', 'completed', 'cancelled')", name='ck_treatment_status'),
    sa.CheckConstraint('tooth_number IS NULL OR (tooth_number >= 1 AND tooth_number <= 32)', name='ck_treatment_tooth_number'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('treatments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_treatments_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_treatments_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_treatments_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_treatments_patient_id'), ['patient_id'], unique=False)

    op.create_table('x_rays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('original_mime_type', sa.String(length=100), nullable=True),
    sa.Column('tooth_tag', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('x_rays', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_x_rays_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_x_rays_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_x_rays_uploaded_by'), ['uploaded_by'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('treatment_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('unpaid', 'partially-paid', 'paid', 'cancelled')", name='ck_invoice_status'),
    sa.CheckConstraint('amount >= 0', name='ck_invoice_amount'),
    sa.CheckConstraint('discount >= 0', name='ck_invoice_discount'),
    sa.CheckConstraint('paid_amount >= 0', name='ck_invoice_paid_amount'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_treatment_id'), ['treatment_id'], unique=False)

    op.create_table('prescription_medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=True),
    sa.Column('frequency', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prescription_medications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescription_medications_prescription_id'), ['prescription_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_clinic_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key('fk_users_clinic_id_clinics', 'clinics', ['clinic_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_clinic_id_clinics', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('users_clinic_id_fkey'), 'clinics', ['clinic_id'], ['id'])

    with op.batch_alter_table('prescription_medications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescription_medications_prescription_id'))

    op.drop_table('prescription_medications')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_treatment_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_patient_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_created_by'))
        batch_op.drop_index(batch_op.f('ix_invoices_clinic_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('x_rays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_x_rays_uploaded_by'))
        batch_op.drop_index(batch_op.f('ix_x_rays_patient_id'))
        batch_op.drop_index(batch_op.f('ix_x_rays_clinic_id'))

    op.drop_table('x_rays')
    with op.batch_alter_table('treatments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_treatments_patient_id'))
        batch_op.drop_index(batch_op.f('ix_treatments_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_treatments_created_by'))
        batch_op.drop_index(batch_op.f('ix_treatments_clinic_id'))

    op.drop_table('treatments')
    with op.batch_alter_table('treatment_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_treatment_plans_patient_id'))
        batch_op.drop_index(batch_op.f('ix_treatment_plans_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_treatment_plans_created_by'))
        batch_op.drop_index(batch_op.f('ix_treatment_plans_clinic_id'))

    op.drop_table('treatment_plans')
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescriptions_patient_id'))
        batch_op.drop_index(batch_op.f('ix_prescriptions_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_prescriptions_created_by'))
        batch_op.drop_index(batch_op.f('ix_prescriptions_clinic_id'))

    op.drop_table('prescriptions')
    with op.batch_alter_table('odontograms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_odontograms_patient_id'))
        batch_op.drop_index(batch_op.f('ix_odontograms_created_by'))
        batch_op.drop_index(batch_op.f('ix_odontograms_clinic_id'))

    op.drop_table('odontograms')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_patient_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_date'))
        batch_op.drop_index(batch_op.f('ix_appointments_created_by'))
        batch_op.drop_index(batch_op.f('ix_appointments_clinic_id'))

    op.drop_table('appointments')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_phone'))
        batch_op.drop_index(batch_op.f('ix_patients_created_by'))
        batch_op.drop_index(batch_op.f('ix_patients_clinic_id'))

    op.drop_table('patients')
    # ### end Alembic commands ###
