"""Remove redundant foreign keys

Revision ID: 647b6203aff5
Revises: f1670d3de2c4
Create Date: 2026-09-20 16:24:51.143856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647b6203aff5'
down_revision = 'f1670d3de2c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('appointments_created_by_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('appointments_patient_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('appointments_doctor_id_fkey'), type_='foreignkey')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('invoices_treatment_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('invoices_patient_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('invoices_created_by_fkey'), type_='foreignkey')

    with op.batch_alter_table('odontograms', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('odontograms_created_by_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('odontograms_patient_id_fkey'), type_='foreignkey')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('patients_created_by_fkey'), type_='foreignkey')

    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('prescriptions_doctor_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('prescriptions_patient_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('prescriptions_created_by_fkey'), type_='foreignkey')

    with op.batch_alter_table('treatment_plans', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('treatment_plans_doctor_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('treatment_plans_patient_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('treatment_plans_created_by_fkey'), type_='foreignkey')

    with op.batch_alter_table('treatments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('treatments_created_by_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('treatments_doctor_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('treatments_patient_id_fkey'), type_='foreignkey')
    with op.batch_alter_table('x_rays', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('x_rays_patient_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('x_rays_uploaded_by_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('x_rays', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('x_rays_uploaded_by_fkey'), 'users', ['uploaded_by'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('x_rays_patient_id_fkey'), 'patients', ['patient_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('treatments', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('treatments_patient_id_fkey'), 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('treatments_doctor_id_fkey'), 'users', ['doctor_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('treatments_created_by_fkey'), 'users', ['created_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('treatment_plans', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('treatment_plans_created_by_fkey'), 'users', ['created_by'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('treatment_plans_patient_id_fkey'), 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('treatment_plans_doctor_id_fkey'), 'users', ['doctor_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('prescriptions_created_by_fkey'), 'users', ['created_by'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('prescriptions_patient_id_fkey'), 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('prescriptions_doctor_id_fkey'), 'users', ['doctor_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('patients_created_by_fkey'), 'users', ['created_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('odontograms', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('odontograms_patient_id_fkey'), 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('odontograms_created_by_fkey'), 'users', ['created_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('invoices_created_by_fkey'), 'users', ['created_by'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('invoices_patient_id_fkey'), 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('invoices_treatment_id_fkey'), 'treatments', ['treatment_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('appointments_doctor_id_fkey'), 'users', ['doctor_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('appointments_patient_id_fkey'), 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('appointments_created_by_fkey'), 'users', ['created_by'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
